cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import get_main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_main, name='main'),
    path('order/', include('order.urls')),
    path('service/', include('service.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('myaccount.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_services_list, name='services_list'),
    # path('entries/', views.EntriesView.as_view(), name='entries'),
    path('entries/', views.entries_time, name='entries'),
    path('<str:category_slug>/', views.get_barbers_list, name='barber_list_by_category'),
]

service/models.py
from django.contrib.admin.widgets import AdminDateWidget
from django.db import models
from django.urls import reverse
from myaccount.models import MyUser



class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='media', blank=True)
    description = models.TextField()


    class Meta:
        ordering = ('title', )
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('services_list',
                       args=[self.slug, ])

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url


class Barber(models.Model):
    category = models.ForeignKey(Category, related_name='cat_ber', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=55)
    description = models.TextField()
    image = models.ImageField(upload_to='media', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'барбер'
        verbose_name_plural = 'барберы'

    def __str__(self):
        return f'{self.name} {self.last_name}'




class EntriesTime(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='entruser')
    date = models.DateField()
    time = models.TimeField()

service/forms.py
from django import forms
from .models import EntriesTime



class EntriesForm(forms.ModelForm):
    class Meta:
        model = EntriesTime
        exclude = ('user', )

service/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from shop.forms import CommentForm
from .models import *
from django.shortcuts import render, get_object_or_404
from .helpers import barber_list_filter_sort
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import *


def get_services_list(request):
    categories = Category.objects.all()
    return render(request, 'service.html', {'categories': categories})


def get_barbers_list(request, category_slug=None):
    """
    Функция вытаскивает барберов и если слаг приходит заполненным,
    то фильтрует по слагу и в конце вовращаем контексты
    """
    category = None
    barbers = Barber.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        barbers = barbers.filter(category=category)
        barbers = barber_list_filter_sort(
            request,
            barbers,
            category_slug
        )

    paginator = Paginator(barbers, settings.PAGINATOR_NUM)
    page_number = request.GET.get('page')
    barbers = paginator.get_page(page_number)

    context = {
        'barbers': barbers,
        'category': category,
    }
    return render(
        request,
        'barbers_list.html',
        context=context
    )







@login_required()
def entries_time(request):
    if request.method == "POST":
        form = EntriesForm(data=request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
    form = EntriesForm()
    return render(request, 'entries.html', {'form': form})

service/templates/barbers_list.html
{% extends 'base.html' %}
{% load static %}
{%block title%}
Barbers:
{% endblock %}

{% block content %}
    <section class="features">
        <div id="sidebar">
            <div style="margin-left: 40px; margin-top: 120px;">
                <a href="{% url 'barber_list_by_category' category.slug %}?-price=sort">
                  <button class="btn btn-outline-primary">Expensive</button>
                </a>
                <a href="{% url 'barber_list_by_category' category.slug %}?price=sort">
                  <button class="btn btn-outline-primary">Low</button>
                </a>
            </div>
        </div>
    </section>


    <article>
            <div style="display:flex;flex-wrap:wrap;align-content: center;justify-content: space-between;width: 80vw;">
            {% for barber in barbers %}
                <div style=" margin-left: 40px;">
                <img src="{{barber.image.url}}" alt="" style="weight: 550px; height: 350px;"/>
                <h1 class="major">{{barber.name}} {{barber.last_name}}</h1>
                <p> {{barber.description}} </p>
                <h3 class="major">{{barber.price}} $</h3>
                  <a href="{% url 'entries' %}"><button type="submit" name="Submit" class="btn btn-secondary">Записаться</button></a>
                </div>
            </div>
            {% endfor %}
        </article>


        {% if barbers %}
			<div class="pagination">
			<span class="step-links">
        {% if barbers.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a class="w3-left w3-btn" href="?page={{ barbers.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ barbers.number }} of {{ barbers.paginator.num_pages }}.
        </span>

        {% if barbers.has_next %}
            <a class="w3-right w3-btn" href="?page={{ barbers.next_page_number }}">next</a>
            <a href="?page={{ barbers.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
		</span>
		</div>
		{% endif %}

{% endblock %}

service/templates/entries.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block content %}

    <div style="display: flex; flex-direction: column; align-items: center; justify-content: left; height: 80vh; margin-top: 200px;">
        <form method='post' style="display: flex; flex-direction: column;">
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit' name="Submit" value='Записаться'>
        </form>
    </div>


<script>
    let date = $("#id_date");
    date.attr('type', 'date');
    date.attr('style', 'background-color:rgba(255, 255, 255, 0);appearance: none;background: rgba(255, 255, 255, 0.025);border-radius: 5px;border: none;border: solid 2px rgba(255, 255, 255, 0.125);color: inherit;display: block;outline: 0;padding: 0 1em;text-decoration: none;width: 100%;')
    let time = $("#id_time");
    time.attr('type', 'time');
    time.attr('style', 'background-color:rgba(255, 255, 255, 0);appearance: none;background: rgba(255, 255, 255, 0.025);border-radius: 5px;border: none;border: solid 2px rgba(255, 255, 255, 0.125);color: inherit;display: block;outline: 0;padding: 0 1em;text-decoration: none;width: 100%;')
</script>
{% endblock content %}

service/templates/service.html
<!DOCTYPE HTML>
{% extends 'base.html' %}
{% load static %}
{%block title%}
Услуги
{% endblock %}

{% block content %}
<section id="wrapper">
	<header>
		<div class="inner">
			<h2>Услуги Барбершопа</h2>
			<p>В наше время индустрия моды регулярно предлагает нам свежие тренды, стираются многолетние стереотипы, которые связаны с модой и стилем. Мужчины отдают предпочтение окрашиванию волос и креативным, модным стрижкам. Ведь современный мужчина с качественной длинной или короткой прической неизменно выглядит уверенно и представительно.

				Сейчас не столь важен цвет, форма стрижки или аксессуары, как сами волосы, их здоровье и ухоженный вид, поэтому необходимо стричься у профессионала своего дела. Мы отлично разбираемся в этом, мужские стрижки и бритье — наша специализация, работы наших мастеров оценены по достоинству каждым, кто приходит в Men's Club 13.</p>
		</div>
	</header>

	<!-- Content -->
		<div class="wrapper">
			<div class="inner">

				<h3 class="major">МУЖСКИЕ
					СТРИЖКИ</h3>
				<p>Чтобы облегчить Вам выбор и определить желаемый стиль стрижки, Men's Club 13 представляет Вашему вниманию некоторые виды и названия модельных мужских стрижек, которые мы с удовольствием сделаем для Вас!</p>

				<h3 class="major">Стрижка усов и бороды, оформление</h3>
				<p>Борода и усы для мужчины важная особенность издревле. И если вы думаете, что «отпустить бороду» или «отрастить усы» — значит просто дать волосам на лице расти как они хотят, то вы сильно ошибаетесь. За ними нужен особый уход как ежедневный, так и профессиональный.</p>

							<div style="display:flex;flex-wrap:wrap;align-content: center;justify-content: space-between;width: 80vw;">
							{% for cat in categories %}
							<div style="margin-top: 30px; ">
								<img src="{{ cat.image_url}}" alt="" style="weight: 250px; height: 250px;"/>
								<h3 class="major">{{cat.title}}</h3>
								<p> {{cat.description}}</p>
								<a href="{% url 'barber_list_by_category' cat.slug  %}"><button type="submit" name="Submit" class="btn btn-secondary">Выбрать</button></a>
							</div>
							{% endfor %}
							</div>

			</div>
		</div>

</section>
{%endblock%}
